version: '3.5'

services:
  php:
    container_name: ${APP_NAME:-app}_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - APP_DEBUG=${APP_DEBUG:-1}
    volumes:
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/config/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/var/www/app
      - .composer/cache:/home/www-data/.composer/cache
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-net

  nginx:
    container_name: ${APP_NAME:-app}_nginx
    image: nginx:1.25-alpine
    volumes:
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app
    ports:
      - "${NGINX_PORT:-80}:80"
    networks:
      - app-net

networks:
  app-net:
    name: ${APP_NAME:-app}_network
